### ISSUE TITLE
Vite default port is 5173

### ISSUE THREAD

**Issue by gimntut** [webix-hub/gitbook-webix-jet#15]
The documentation [specifies the default port 8080](https://github.com/search?q=repo%3Awebix-hub%2Fgitbook-webix-jet%208080&type=code), but in reality the default port is 5173.

![image](https://github.com/webix-hub/gitbook-webix-jet/assets/1645084/3865b221-f125-4785-9951-4615f08e1227)

**Comment by kullias** [comment]
Hi,
yes, you are right, the docs still tells about the webpack default port, we'll add the vite default port. Thanks for reporting this.
