### ISSUE TITLE
Clarification about options parameter of the IJetRouter#set(path, config) method is necessary

### ISSUE THREAD

**Issue by alexandrklimov** [webix-hub/gitbook-webix-jet#2]
Hello Webix team!

Could you provide some additional information about the **options** argument of the **IJetRouter#set(path, config)** method, please?

What options can I provide in this hash?

**Comment by kullias** [comment]
Hello!
**config** can contain the **silent** flag. By default, when the URL is changed, the callback (from the constructor) is called and the UI is refreshed. If `silent:true`, the callback is not called.
