### ISSUE TITLE
UrlParam plugin section about getParam method

### ISSUE THREAD

**Issue by alexandrklimov** [webix-hub/gitbook-webix-jet#3]
In the doc., usage of the getParam method is defined as
`this.getParam("id");`

But this method is defined with two arguments in the JetBase class
`getParam(id:string, parent:boolean):any`

**Comment by kullias** [comment]
Thanks for reporting, I will complete the section in the book.

**Comment by kullias** [comment]
hm, as far as I can see, the second parameter is already there in the API section https://github.com/webix-hub/gitbook-webix-jet/blob/master/part-ii-webix-jet-in-details/jetview-api.md (line 7 and 27). I will see to the page on Plugins and will either add the second parameter to the text there or provide a link to the API page.

**Comment by kullias** [comment]
Yep, I checked the page on plugins, and the method is definitely called there with only one parameter, but the second parameter is not needed there, so it is not mentioned.  It doesn't say in any way that there is only one parameter.
So to avoid ambiguity and misundestanding, I will just add a link to the API. Thanks again for reporting.
