### ISSUE TITLE
When was the last update?

### ISSUE THREAD

**Issue by dandv** [webix-hub/gitbook-webix-jet#4]
![image](https://user-images.githubusercontent.com/33569/42720380-cd04354e-86da-11e8-82d9-eece1e28ee76.png)

**Comment by kullias** [comment]
Hi!

New GitBook marks the last update for every page on its own (the first date). The second date is changed by me every time I push something to 'master'. So really the last update date can be viewed either in the second line or better still in the log of commits. Or on the page(s) that was(were) updated.

Quite surprisingly, though I changed the **readme** file as well during the last commit, GitBook didn't count it as an update of this particular page. However, it did count the last date correctly for this page, e.g. https://www.screencast.com/t/ECnEgv9OBiA (which was 5 days ago, July 11)
