### ISSUE TITLE
Move "What's New", "Quick Development Guidelines" and "Migrating" to the end of the book

### ISSUE THREAD

**Issue by dandv** [webix-hub/gitbook-webix-jet#8]
Given that most users who read a book on Jet are likely to be new to Jet, it makes sense that the first chapter after [the home page](https://webix.gitbook.io/webix-jet/) should be "Getting Started". I'm new to Jet, and saw that the first chapter after the home page was [What's New](https://webix.gitbook.io/webix-jet/whats-new), which didn't make sense to me.

Similarly, [Getting Started](https://webix.gitbook.io/webix-jet/getting-started) should be followed by Part I, not by the [Quick Development Guidelines](https://webix.gitbook.io/webix-jet/quick-development-guidelines), which a new user doesn't know what to do with (what's the "app:error:resolve" event? [where is the app config?](https://github.com/webix-hub/gitbook-webix-jet/issues/7) etc.)

Same for the Migrating chapter. These three chapters belong to the end of the book.

**Comment by kullias** [comment]
Yes, good point. Thanks for the suggestion.
