### ISSUE TITLE
Use UrlRouter by default?

### ISSUE THREAD

**Issue by dandv** [webix-hub/gitbook-webix-jet#9]
The book uses HashRouter by default, and has to explain what a hashbang is in the [Getting Started](https://webix.gitbook.io/webix-jet/getting-started) chapter. Hashbangs are ugly, deprecated, and modern web apps no longer use them. I [posted about this on the forum two years ago](https://forum.webix.com/discussion/7161/routing-with-traditional-url-paths-instead-of-the-hashbang-convention).

Using UrlRouter would and make the app look more modern, at the expense of some [more setup on the server](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/routers#2-url-router).

**Comment by kullias** [comment]
>The book uses HashRouter by default

Well, the book just tells that Jet uses it by default :)
Thanks, I will add a line about the hashbang in the chapter.

**Comment by mkozhukh** [comment]
UrlRouter in the production app requires special configuration from a server-side ( URL redirects )
HashRouter doesn't require any extra configuration, so it is more suitable for "Getting Started"

The code itself allows to use [any kind of routing](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/routers) as well as  [customize the hashbang content](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/routers#hiding-the-in-the-url).
